start:
	python manage.py runserver

# Collects all the frontend files from the most recent build and
# returns them for certain endpoints 
static:
	python manage.py collectstatic

startdev:
	python manage.py runserver

format:
	black .

# Command to start virtual environment
# source env/bin/activate